### ISSUE TITLE
New ItemPipe Type: Sorting Pipe

### ISSUE THREAD

**Issue by anuar2k** [Terasology/AdditionalItemPipes#1]
The Sorting Pipe would let player decide what items would go which way. It would have one input side and up to 5 output sides.

Upon activation, an UI screen would show up used to configure the pipe.

One of these sides should be used to pass items which would not have been defined in the settings of the pipe.

**Comment by pollend** [comment]
why not just have it choose based on the other output sides based on where an item came in as input.  you wouldn't need to define an input side.

**Comment by syntaxi** [comment]
Could you describe the GUI a little bit please? How do you specify the sides? Are they absolute (North, South, East, West, Up, Down)? Are they relative (Left, Right, Up, Down, Foward, Back)?

Would the one input side always be the same. eg, up? What if the player is in a situation where they can't easily run a pipe to the input side? If the input side isn't always the same how is it selected? How does changing the input effect the outputs if the pipe uses relative? How about if it uses absolute?

I'd like to see a little bit more info overall but I do quite like the idea. The reason I'm being so picky is that I think it's a crucial pipe and as such the pipe should be solidly thought out.

**Comment by anuar2k** [comment]
The sides of the pipe would be absolute. The UI Screen would consist of 6 rows of InventoryGrid, with two checkboxes on the right of each row to select the input side and side for non-filtered items.

**Comment by anuar2k** [comment]
In my opinion it would be better to have a static input side to prevent players from coming up with an idea of using the same side for pushing items into the sorting pipe, and getting them out of it.
