### ISSUE TITLE
New BLock: Unificator

### ISSUE THREAD

**Issue by alberto512** [Terasology/AdditionalItemPipes#4]
The unificator will be a block that needs to have one output and at least two inputs. To diferenciate the inputs and the outputs, the unificator will open an UI screen where you will select which side of the block will contain the output. The other sides will be the input

**Comment by syntaxi** [comment]
I like this idea. So it functions much as a One Way valve.
Could you just add a little bit more detail on how the UI will work. How will you refer to the sides in it? Will you use similar methods like the Sort Block?
What will happen if the output side is removed without changing it in the UI? How about if an output is not selected?

**Comment by alberto512** [comment]
The unificator will be a block that needs to have one output and at least two inputs. To diferenciate the inputs and the outputs, the unificator will open an UI screen where you will select which side of the block will contain the output. The other sides will be the input. Each side will have a number (You can see the number in each side of the block), and in the UI screen you will choose the number of you output. If you don't select the output or if you remove the output without changing it in the UI, the output will be the lowest number with a pipe. And if you don't have three pipes attached to it, the block will work as a pipe that only have one connection, that means that the items will fall to the ground

**Comment by Cervator** [comment]
Rather than a UI screen, couldn't the user just `e` or right click the block with some tool and the face the player touches becomes the output? Anything else is input.

That would require x variant blocks to make the output visually distinct then just swap in the right one when an action is taken

**Comment by pollend** [comment]
I would also like this to be a pipe but that may be fairly difficult with how block families work but getting that to work would be really nice.

**Comment by alberto512** [comment]
I have made the unificator block, that will work if it has at least two connections
