### ISSUE TITLE
New Block: Variable Output Splitter

### ISSUE THREAD

**Issue by Steampunkery** [Terasology/AdditionalItemPipes#7]
This block is like a splitter on a hose. There is one pipe that brings input to the block. All of the other sides could be outputs. Each side that has a pipe attached that isn't an input is an output. The block alternates between all of the output pipes, putting the next item from input in each successive pipe. When all of the outputs have gotten an item, it wraps back around to the first output and starts again. Thus, the input is split evenly between all of the output pipes. This pipe has a practical use in splitting items between between workstations or chests.

**Comment by pollend** [comment]
pure random chance has the same distribution as well?

**Comment by syntaxi** [comment]
Okay, so I like the core concept, being able to control the distribution of items between outputs, however like Pollend said, random distribution also evenly splits the items.

Is there someway you can make the pipe more configurable? A way that makes it more generic?

**Comment by Steampunkery** [comment]
@jellysnake , that's just the sorter block. I'm going back to the farming idea.
