### ISSUE TITLE
New Block Idea: Pipe Switch

### ISSUE THREAD

**Issue by sagarg22** [Terasology/AdditionalItemPipes#8]
This doesn't necessarily have to be a literal "block", but more of an "add on". Essentially, this is a switch/lever that can be placed on pipes and when acted upon, disable or enable the item pipe. In this case, disabling and enabling refers to stopping the flow of items from the pipe to the deposit. For example, if a Suction Block sucked in an item and was transporting it through a pipe to a chest, but one of the pipes in the chain had a switch on it that was enabled, the item would stop and not be able to move through the pipe until the switch was enabled again.

The implementation of this concept does not require the integration of any other modules. However, instead of changing the coding of the original pipe to allow this, there is also the option of creating a new type of pipe that is the only kind that can be enabled or disabled. By using this method, players can stop the transportation of items after a certain amount of time and control the pipes however they want to.

**Comment by pollend** [comment]
What do you do when all the items pile up in the pipe. You have to put them somewhere. the way you would do this is place the items in a buffer chest.

**Comment by sagarg22** [comment]
Yeah, but would it be possible to just stop more items from entering the pipe?

**Comment by pollend** [comment]
you have a chain of pipes. how do you plan to stop items in the chain? Items are not aware of their neighbors in the pipe and will overlap each other if that occurs.

**Comment by sagarg22** [comment]
Oh, I see your point. Maybe instead of a switch, there could be a block that can hold items (like a chest) and keep them from getting "extracted" out.

**Comment by pollend** [comment]
You can already do that with a chest in the base module. The extraction pipe is one of the other issues in this issue tracker.

**Comment by sagarg22** [comment]
Ok, I will come up with a new idea then.
